import en from './en'
import type { Dictionary } from './pl'

const de: Dictionary = {
  ...en,
  meta: { ...en.meta, title: 'SilvoTech — Hersteller von Silikonschläuchen in Europa', description: 'Transparente Silikonschläuche für Lebensmittelkontakt und schwarze technische Silikonschläuche. B2B-Produktion und Vertrieb in Europa.' },
  nav: { products: 'Produkte', specification: 'Größen', production: 'Über uns', quality: 'Dokumente', industries: 'Zusammenarbeit', contact: 'Kontakt', cta: 'Angebot anfordern', menu: 'Menü', close: 'Schließen', language: 'Sprache' },
  hero: { ...en.hero, eyebrow: 'Hersteller und Distributor in Europa', title: 'Silikonschläuche für Industrie und Lebensmittelanwendungen', lead: 'Wir liefern transparente, für den Lebensmittelkontakt geeignete Silikonschläuche sowie schwarze Schläuche für technische Anwendungen. Großhandelspreise werden individuell kalkuliert.', primaryCta: 'Angebot anfordern', secondaryCta: 'Produkte ansehen', facts: [{ value: '-50 bis +230 °C', label: 'Einsatzbereich' }, { value: '20 m', label: 'Standardrolle' }, { value: '28', label: 'Standardgrößen' }, { value: 'Europa', label: 'Produktion und Vertrieb' }] },
  products: { ...en.products, eyebrow: 'Sortiment', title: 'Zwei Kategorien. Klare Anwendungen.', lead: 'Wir fertigen Standardvarianten und jede Sondergröße auf Anfrage. Jedes Großhandelsangebot wird individuell erstellt.', labels: { ...en.products.labels, sizes: 'Innen- / Außendurchmesser (mm)', temperature: 'Einsatzbereich', pressure: 'Parameter', packaging: 'Verfügbarkeit', standards: 'Dokumentation', cta: 'Großhandelspreis anfragen' }, items: { clear: { name: 'Transparenter Silikonschlauch', tagline: 'Für den Lebensmittelkontakt geeignet', description: 'Flexibler transparenter Silikonschlauch für Anwendungen mit visueller Durchflusskontrolle und Lebensmittelkontakt.', features: ['28 Standardgrößen', 'Jede Sondergröße auf Anfrage', 'Erklärung und Prüfberichte auf Anfrage'] }, technical: { name: 'Schwarzer Silikonschlauch', tagline: 'Für technische Anwendungen', description: 'Schwarzer Silikonschlauch für technische Anlagen und Prozesse. Maße und Parameter werden an die Anwendung angepasst.', features: ['Individuelle Abmessungen', 'Bereich von -50 °C bis +230 °C', 'B2B-Produktion'] } } },
  specs: { ...en.specs, eyebrow: 'Größen und Verfügbarkeit', title: '28 Standardgrößen', lead: 'Die Maße sind Innen- / Außendurchmesser. Weitere Größen fertigen wir auf Anfrage.', note: 'Druckparameter hängen von Abmessung, Temperatur und Anwendung ab und werden im Angebot individuell bestätigt.' },
  production: { ...en.production, eyebrow: 'Produktion und Vertrieb', title: 'B2B-Partner für den europäischen Markt', lead: 'Als Hersteller und Distributor beliefern wir Industrie, Lebensmittelbranche und Großhandel in Europa.' },
  quality: { ...en.quality, eyebrow: 'Konformität und Prüfungen', title: 'Dokumente auf Anfrage', lead: 'Die Konformitätserklärung bestätigt die Übereinstimmung des geprüften Erzeugnisses mit den Anforderungen der Verordnung (EG) Nr. 1935/2004 und des deutschen LFGB im Umfang der durchgeführten Laborprüfungen.' },
  rfq: { ...en.rfq, eyebrow: 'Großhandelsanfrage', title: 'Individuelles Angebot erhalten', lead: 'Nennen Sie Kategorie, Größe und Menge. Wir antworten mit Großhandelspreis, Lieferzeit und verfügbarer Dokumentation.', fields: { ...en.rfq.fields, company: 'Firma', name: 'Ansprechpartner', email: 'Geschäftliche E-Mail', phone: 'Telefon', country: 'Land', product: 'Produktkategorie', productPlaceholder: 'Kategorie wählen', productOther: 'Ich brauche Beratung', size: 'Größe', sizePlaceholder: 'Standardgröße wählen', sizeCustom: 'Andere Größe — unten beschreiben', quantity: 'Menge (m / Rollen)', message: 'Nachricht', messagePlaceholder: 'Anwendung, gewünschte Größe und geplante Menge beschreiben.', optional: 'optional' }, submit: 'Anfrage senden', submitting: 'Wird gesendet…', successTitle: 'Ihre Anfrage wurde gesendet', successText: 'Vielen Dank. Wir antworten per E-Mail. Dringend: +48 573 569 216.', errorText: 'Senden fehlgeschlagen. sales@silvotech.eu oder +48 573 569 216.', required: 'Firma, Ansprechpartner und gültige E-Mail ausfüllen.', privacy: 'Wir nutzen Ihre Daten nur zur Angebotserstellung.', asideTitle: 'Direkter Kontakt', asideAddress: 'Firmensitz / Kundenservice' },
  footer: { ...en.footer, tagline: 'Hersteller und Distributor von Silikonschläuchen in Europa. Individuelle Großhandelsangebote.', productsTitle: 'Produkte', contactTitle: 'Kontakt', nip: 'USt-IdNr.', rights: 'Alle Rechte vorbehalten.', addressLabel: 'Firmensitz / Kundenservice' }
}
export default de
