import pl, { type Dictionary } from './pl'

const en: Dictionary = {
  ...pl,
  meta: { title: 'SilvoTech — silicone hose manufacturer in Europe', description: 'Transparent food-contact silicone tubing and black technical silicone hoses. B2B manufacturing and distribution across Europe, 20 m coils and custom sizes.', keywords: 'silicone hose, food contact tubing, technical hose, manufacturer, wholesale, LFGB, 1935/2004', ogAlt: 'SilvoTech silicone hose production' },
  nav: { products: 'Products', specification: 'Sizes', production: 'About us', quality: 'Documents', industries: 'Cooperation', contact: 'Contact', cta: 'Request a quote', menu: 'Menu', close: 'Close', language: 'Language' },
  hero: { eyebrow: 'Manufacturer and distributor in Europe', title: 'Silicone hoses for industry and food applications', lead: 'We supply transparent silicone tubing suitable for food contact and black hoses for technical applications. Wholesale prices are quoted individually.', primaryCta: 'Request a quote', secondaryCta: 'View products', imageAlt: 'Transparent silicone hose on a production line', facts: [{ value: '-50 to +230 °C', label: 'Operating range' }, { value: '20 m', label: 'Standard coil' }, { value: '28', label: 'Standard sizes' }, { value: 'Europe', label: 'Manufacturing and distribution' }] },
  logos: { title: 'Key information', items: ['Silicone', 'B2B', '20 m', '1935/2004', 'LFGB'] },
  products: { ...pl.products, eyebrow: 'Product range', title: 'Two categories. Clear applications.', lead: 'We manufacture standard variants and any custom dimension on request. Every wholesale quotation is prepared individually.', labels: { ...pl.products.labels, sizes: 'Inner / outer diameter (mm)', sizesSimple: 'Sizes', temperature: 'Operating range', pressure: 'Parameters', packaging: 'Availability', standards: 'Documentation', cta: 'Request wholesale pricing' }, items: {
    clear: { name: 'Transparent silicone tubing', tagline: 'Suitable for food contact', description: 'Flexible transparent silicone tubing for applications requiring visual flow control and material suitable for food contact.', features: ['28 standard sizes', 'Any custom size on request', 'Declaration and test results available on request'] },
    technical: { name: 'Black silicone hose', tagline: 'For technical applications', description: 'Black silicone hose for technical installations and processes. Dimensions and parameters are selected for the specific application.', features: ['Dimensions quoted individually', 'Range from -50 °C to +230 °C', 'B2B manufacturing'] }
  } },
  specs: { ...pl.specs, eyebrow: 'Sizes and availability', title: '28 standard sizes', lead: 'Dimensions are inner / outer diameter. Other sizes can also be manufactured on request.', columns: { product: 'Product', sizes: 'Sizes (mm)', temperature: 'Range', pressure: 'Parameters', packaging: 'Coil', standards: 'Documentation' }, note: 'Pressure parameters depend on dimensions, temperature and application; we confirm them individually with the quotation.' },
  production: { ...pl.production, eyebrow: 'Manufacturing and distribution', title: 'A B2B partner for the European market', lead: 'As a manufacturer and distributor, we serve industrial, food and wholesale customers across Europe.', blocks: [{ title: 'Custom manufacturing', text: 'In addition to 28 standard variants, we manufacture dimensions for your application.' }, { title: 'Wholesale supply', text: 'Pricing, volumes and delivery schedules are agreed individually.' }, { title: '20 m coils', text: 'Standard product availability is in 20-metre coils.' }, { title: 'European service', text: 'We manufacture and distribute hoses to B2B customers across Europe.' }] },
  quality: { ...pl.quality, eyebrow: 'Compliance and testing', title: 'Documents available on request', lead: 'The declaration of conformity states that the tested product complies with the requirements of Regulation (EC) No 1935/2004 and the German LFGB, within the scope of the laboratory tests performed.', items: [{ title: 'Regulation (EC) No 1935/2004', text: 'The scope of conformity applies to the tested product and laboratory tests performed.' }, { title: 'German LFGB', text: 'The test results were prepared by a German laboratory.' }, { title: 'Documents on request', text: 'We provide the declaration and laboratory test results to interested customers.' }, { title: 'Application review', text: 'Before purchase, we confirm the medium, temperature and operating requirements.' }], docsTitle: 'Available from us', docs: ['Declaration of conformity for the tested product', 'German laboratory test results', 'Dimensional specification', 'Commercial offer and lead time'] },
  industries: { ...pl.industries, eyebrow: 'Cooperation', title: 'For industry, food processing and distribution', items: [{ title: 'Food industry', text: 'Transparent tubing for applications requiring material suitable for food contact.', points: ['Visual flow control', 'Documents on request', 'Standard and custom sizes'] }, { title: 'Manufacturing plants', text: 'Black and transparent hoses selected for installation parameters and planned consumption.', points: ['Technical selection', 'Repeat deliveries', 'Custom dimensions'] }, { title: 'Distributors', text: 'Wholesale terms, regular deliveries and offers tailored to the cooperation model.', points: ['Individual pricing', 'European delivery', 'Manufacturer and distributor'] }] },
  rfq: { ...pl.rfq, eyebrow: 'Wholesale enquiry', title: 'Receive an individual quotation', lead: 'Specify the category, size and quantity. We will reply with wholesale pricing, lead time and available documentation.', fields: { ...pl.rfq.fields, company: 'Company', name: 'Contact person', email: 'Business email', phone: 'Phone', country: 'Country', product: 'Product category', productPlaceholder: 'Select a category', productOther: 'I need help selecting', size: 'Size', sizePlaceholder: 'Select a standard size', sizeCustom: 'Other size — describe it below', quantity: 'Quantity (m / coils)', message: 'Message', messagePlaceholder: 'Describe the application, required size and planned volume.', optional: 'optional' }, submit: 'Send enquiry', submitting: 'Sending…', successTitle: 'Your enquiry has been sent', successText: 'Thank you. We will reply by email. For urgent matters call +48 573 569 216.', errorText: 'The message could not be sent. Email sales@silvotech.eu or call +48 573 569 216.', required: 'Complete the company, contact person and a valid email address.', privacy: 'We use your data only to prepare the offer.', asideTitle: 'Direct contact', asideAddress: 'Registered office / customer service' },
  footer: { ...pl.footer, tagline: 'Silicone hose manufacturer and distributor in Europe. Individual wholesale quotations.', productsTitle: 'Products', contactTitle: 'Contact', nip: 'VAT ID', rights: 'All rights reserved.', addressLabel: 'Registered office / customer service' }
}
export default en
