const pl = {
  meta: { title: 'SilvoTech — producent węży silikonowych w Europie', description: 'Przezroczyste węże silikonowe do kontaktu z żywnością i czarne węże techniczne. Produkcja i dystrybucja B2B w Europie, rolki 20 mb, rozmiary na zamówienie.', keywords: 'wąż silikonowy, wężyk spożywczy, wąż techniczny, producent, hurt, LFGB, 1935/2004', ogAlt: 'Produkcja węża silikonowego SilvoTech' },
  nav: { products: 'Produkty', specification: 'Rozmiary', production: 'O nas', quality: 'Dokumenty', industries: 'Współpraca', contact: 'Kontakt', cta: 'Zapytaj o wycenę', menu: 'Menu', close: 'Zamknij', language: 'Język' },
  hero: { eyebrow: 'Producent i dystrybutor w Europie', title: 'Węże silikonowe dla przemysłu i branży spożywczej', lead: 'Dostarczamy przezroczyste węże silikonowe odpowiednie do kontaktu z żywnością oraz czarne węże do zastosowań technicznych. Ceny hurtowe ustalamy indywidualnie.', primaryCta: 'Poproś o ofertę', secondaryCta: 'Zobacz produkty', imageAlt: 'Przezroczysty wąż silikonowy na linii produkcyjnej', facts: [{ value: '-50 do +230 °C', label: 'Zakres operacyjny' }, { value: '20 mb', label: 'Standardowa rolka' }, { value: '28', label: 'Standardowych rozmiarów' }, { value: 'Europa', label: 'Produkcja i dystrybucja' }] },
  logos: { title: 'Najważniejsze informacje', items: ['Silikon', 'B2B', '20 mb', '1935/2004', 'LFGB'] },
  products: { eyebrow: 'Asortyment', title: 'Dwie kategorie. Konkretne zastosowanie.', lead: 'Produkujemy standardowe rozmiary oraz dowolny wymiar na indywidualne zamówienie. Każdą ofertę hurtową przygotowujemy osobno.', labels: { code: 'Indeks', sizes: 'Średnica wewnętrzna / zewnętrzna (mm)', sizesSimple: 'Rozmiary', temperature: 'Zakres pracy', pressure: 'Parametry', packaging: 'Dostępność', standards: 'Dokumentacja', cta: 'Zapytaj o cenę hurtową' }, items: {
    clear: { name: 'Przezroczysty wąż silikonowy', tagline: 'Odpowiedni do kontaktu z żywnością', description: 'Elastyczny, przezroczysty wąż silikonowy do zastosowań wymagających kontroli przepływu i materiału odpowiedniego do kontaktu z żywnością.', features: ['28 standardowych rozmiarów', 'Dowolny rozmiar na zamówienie', 'Deklaracja i wyniki badań dostępne na życzenie'] },
    technical: { name: 'Czarny wąż silikonowy', tagline: 'Do zastosowań technicznych', description: 'Czarny wąż silikonowy przeznaczony do instalacji i procesów technicznych. Wymiary i parametry dobieramy do konkretnej aplikacji.', features: ['Wymiary ustalane indywidualnie', 'Zakres od -50 °C do +230 °C', 'Produkcja dla odbiorców B2B'] }
  } },
  specs: { eyebrow: 'Rozmiary i dostępność', title: '28 standardowych rozmiarów', lead: 'Wymiary podano jako średnica wewnętrzna / zewnętrzna. Poza listą wykonujemy także inne rozmiary na zamówienie.', columns: { product: 'Produkt', sizes: 'Rozmiary (mm)', temperature: 'Zakres', pressure: 'Parametry', packaging: 'Rolka', standards: 'Dokumentacja' }, note: 'Parametry ciśnieniowe zależą od wymiaru, temperatury i aplikacji — potwierdzamy je indywidualnie wraz z ofertą.' },
  production: { eyebrow: 'Produkcja i dystrybucja', title: 'Partner B2B na rynku europejskim', lead: 'Jako producent i dystrybutor obsługujemy odbiorców przemysłowych, spożywczych oraz hurtowych w Europie.', lineImageAlt: 'Detal przezroczystego węża silikonowego', warehouseImageAlt: 'Rolka przezroczystego węża silikonowego', blocks: [
    { title: 'Produkcja na wymiar', text: 'Oprócz 28 standardowych wariantów realizujemy wymiary zgodne z wymaganiami aplikacji.' },
    { title: 'Dostawy hurtowe', text: 'Ceny, wolumeny i harmonogramy dostaw ustalamy indywidualnie dla każdego klienta.' },
    { title: 'Rolki po 20 mb', text: 'Standardowa dostępność produktu to rolki po 20 metrów bieżących.' },
    { title: 'Obsługa w Europie', text: 'Produkujemy i dystrybuujemy węże dla klientów B2B na rynku europejskim.' }
  ] },
  quality: { eyebrow: 'Zgodność i badania', title: 'Dokumenty dostępne na życzenie', lead: 'Deklaracja zgodności stwierdza zgodność badanego wyrobu z wymaganiami Rozporządzenia (WE) nr 1935/2004 oraz niemieckiej ustawy LFGB, w zakresie przeprowadzonych badań laboratoryjnych.', imageAlt: 'Przekrój przezroczystego węża silikonowego', items: [
    { title: 'Rozporządzenie (WE) nr 1935/2004', text: 'Zakres zgodności odnosi się do badanego wyrobu i przeprowadzonych badań laboratoryjnych.' },
    { title: 'Niemiecka ustawa LFGB', text: 'Wyniki badań zostały przygotowane przez niemieckie laboratorium.' },
    { title: 'Dokumenty na zapytanie', text: 'Deklarację zgodności i wyniki badań przekazujemy zainteresowanym klientom.' },
    { title: 'Dobór do aplikacji', text: 'Przed zakupem potwierdzamy wymagania medium, temperatury i warunków pracy.' }
  ], docsTitle: 'Możemy przekazać', docs: ['Deklarację zgodności dla badanego wyrobu', 'Wyniki badań niemieckiego laboratorium', 'Specyfikację wymiarową', 'Informację handlową i termin realizacji'] },
  industries: { eyebrow: 'Współpraca', title: 'Dla przemysłu, branży spożywczej i dystrybucji', items: [
    { title: 'Przemysł spożywczy', text: 'Przezroczyste przewody do aplikacji, w których wymagany jest materiał odpowiedni do kontaktu z żywnością.', points: ['Kontrola przepływu', 'Dokumenty na zapytanie', 'Rozmiary standardowe i specjalne'] },
    { title: 'Zakłady produkcyjne', text: 'Czarne i przezroczyste węże dobierane do parametrów instalacji oraz planowanego zużycia.', points: ['Dobór techniczny', 'Powtarzalne dostawy', 'Indywidualne wymiary'] },
    { title: 'Dystrybutorzy', text: 'Warunki hurtowe, regularne dostawy i oferta przygotowana do modelu współpracy.', points: ['Indywidualne ceny', 'Dostawy w Europie', 'Producent i dystrybutor'] }
  ] },
  rfq: { eyebrow: 'Zapytanie hurtowe', title: 'Otrzymaj indywidualną ofertę', lead: 'Podaj kategorię, rozmiar i planowaną ilość. Odpowiemy ceną hurtową, terminem oraz informacją o dostępnych dokumentach.', fields: { company: 'Firma', name: 'Osoba kontaktowa', email: 'E-mail służbowy', phone: 'Telefon', country: 'Kraj', product: 'Kategoria produktu', productPlaceholder: 'Wybierz kategorię', productOther: 'Potrzebuję pomocy w doborze', size: 'Rozmiar', sizePlaceholder: 'Wybierz standardowy rozmiar', sizeCustom: 'Inny rozmiar — opisz w wiadomości', quantity: 'Ilość (mb / liczba rolek)', message: 'Wiadomość', messagePlaceholder: 'Opisz zastosowanie, wymagany rozmiar i planowany wolumen.', optional: 'opcjonalnie' }, submit: 'Wyślij zapytanie', submitting: 'Wysyłanie…', successTitle: 'Zapytanie zostało wysłane', successText: 'Dziękujemy. Odpowiemy na podany adres e-mail. W pilnych sprawach zadzwoń: +48 573 569 216.', errorText: 'Nie udało się wysłać wiadomości. Napisz na sales@silvotech.eu lub zadzwoń +48 573 569 216.', required: 'Uzupełnij firmę, osobę kontaktową i poprawny adres e-mail.', privacy: 'Dane wykorzystamy wyłącznie do przygotowania oferty.', asideTitle: 'Kontakt bezpośredni', asideAddress: 'Siedziba / biuro obsługi klienta' },
  footer: { tagline: 'Producent i dystrybutor węży silikonowych w Europie. Indywidualne oferty hurtowe.', company: 'Firma', productsTitle: 'Produkty', contactTitle: 'Kontakt', nip: 'NIP', rights: 'Wszelkie prawa zastrzeżone.', addressLabel: 'Adres siedziby / biura obsługi klienta' }
}

export type Dictionary = typeof pl
export default pl
