import type { Locale } from './i18n';

const pl = {
  intro: 'Dobierz produkt do instalacji. Sprawdź wymiary, opisz warunki pracy i prześlij zapytanie o cenę oraz termin dostawy.',
  range: 'Wyroby silikonowe', view: 'Zobacz produkt', sizes: 'Dobierz rozmiar węża',
  sizeHint: 'Średnica wewnętrzna / zewnętrzna, w mm. Wybierz rozmiar, aby przenieść go do zapytania.',
  selected: 'Wybrany rozmiar', choose: 'Wybierz rozmiar', clear: 'Przezroczysty wąż silikonowy',
  custom: 'Potrzebuję innego wymiaru', application: 'Dobór do warunków pracy',
  applicationText: 'Podaj medium, temperaturę, ciśnienie oraz wymiary. Przydatność materiału i wymagane dokumenty potwierdzamy dla konkretnego wyrobu i zastosowania.',
  steps: 'Od specyfikacji do zapytania', step1: 'Wybierz wyrób', step1Text: 'Wąż, płyta, uszczelka lub element według rysunku.',
  step2: 'Podaj warunki pracy', step2Text: 'Wymiary, medium, temperatura, ciśnienie i ilość.',
  step3: 'Prześlij zapytanie', step3Text: 'Poproś o potwierdzenie parametrów, ceny i terminu dostawy.',
  menu: 'Menu główne', open: 'Otwórz menu', close: 'Zamknij menu', language: 'Wybierz język',
  customText: 'Prześlij rysunek lub specyfikację. Wymiary, materiał i termin wymagają indywidualnego potwierdzenia.',
};
export type CatalogCopy = typeof pl;
export const catalogCopy: Record<Locale, CatalogCopy> = {
  pl,
  en: {
    intro: 'Select a product for your installation. Check dimensions, describe the operating conditions and request pricing and a delivery date.',
    range: 'Silicone products', view: 'View product', sizes: 'Choose a hose size',
    sizeHint: 'Inner / outer diameter, in mm. Choose a size to include it in your enquiry.',
    selected: 'Selected size', choose: 'Choose a size', clear: 'Transparent silicone hose',
    custom: 'I need a different size', application: 'Selection for your application',
    applicationText: 'Specify the medium, temperature, pressure and dimensions. Material suitability and required documentation must be confirmed for the specific product and application.',
    steps: 'From specification to enquiry', step1: 'Choose a product', step1Text: 'Hose, plate, gasket or a part made to your drawing.',
    step2: 'Describe the conditions', step2Text: 'Dimensions, medium, temperature, pressure and quantity.',
    step3: 'Send an enquiry', step3Text: 'Request confirmation of specifications, price and delivery date.',
    menu: 'Main navigation', open: 'Open menu', close: 'Close menu', language: 'Select language',
    customText: 'Send a drawing or specification. Dimensions, material and lead time require individual confirmation.',
  },
  de: {
    intro: 'Wählen Sie ein Produkt für Ihre Anlage. Prüfen Sie die Maße, beschreiben Sie die Betriebsbedingungen und fragen Sie Preis und Liefertermin an.',
    range: 'Silikonprodukte', view: 'Produkt ansehen', sizes: 'Schlauchgröße auswählen',
    sizeHint: 'Innen- / Außendurchmesser in mm. Die gewählte Größe wird in Ihre Anfrage übernommen.',
    selected: 'Gewählte Größe', choose: 'Größe auswählen', clear: 'Transparenter Silikonschlauch',
    custom: 'Ich benötige andere Maße', application: 'Auswahl für Ihre Anwendung',
    applicationText: 'Geben Sie Medium, Temperatur, Druck und Maße an. Materialeignung und benötigte Dokumente werden für das konkrete Produkt und die Anwendung bestätigt.',
    steps: 'Von der Spezifikation zur Anfrage', step1: 'Produkt auswählen', step1Text: 'Schlauch, Platte, Dichtung oder ein Teil nach Zeichnung.',
    step2: 'Bedingungen beschreiben', step2Text: 'Maße, Medium, Temperatur, Druck und Menge.',
    step3: 'Anfrage senden', step3Text: 'Lassen Sie sich Parameter, Preis und Liefertermin bestätigen.',
    menu: 'Hauptnavigation', open: 'Menü öffnen', close: 'Menü schließen', language: 'Sprache wählen',
    customText: 'Senden Sie eine Zeichnung oder Spezifikation. Maße, Material und Lieferzeit werden individuell bestätigt.',
  },
  cz: {
    intro: 'Vyberte výrobek pro svou instalaci. Ověřte rozměry, popište provozní podmínky a vyžádejte si cenu a termín dodání.',
    range: 'Silikonové výrobky', view: 'Zobrazit výrobek', sizes: 'Vyberte rozměr hadice',
    sizeHint: 'Vnitřní / vnější průměr v mm. Vybraný rozměr se přenese do poptávky.',
    selected: 'Vybraný rozměr', choose: 'Vyberte rozměr', clear: 'Průhledná silikonová hadice',
    custom: 'Potřebuji jiný rozměr', application: 'Výběr podle provozních podmínek',
    applicationText: 'Uveďte médium, teplotu, tlak a rozměry. Vhodnost materiálu a požadované dokumenty potvrzujeme pro konkrétní výrobek a použití.',
    steps: 'Od specifikace k poptávce', step1: 'Vyberte výrobek', step1Text: 'Hadice, deska, těsnění nebo díl podle výkresu.',
    step2: 'Popište podmínky', step2Text: 'Rozměry, médium, teplota, tlak a množství.',
    step3: 'Pošlete poptávku', step3Text: 'Vyžádejte si potvrzení parametrů, ceny a termínu dodání.',
    menu: 'Hlavní navigace', open: 'Otevřít menu', close: 'Zavřít menu', language: 'Vyberte jazyk',
    customText: 'Pošlete výkres nebo specifikaci. Rozměry, materiál a termín vyžadují individuální potvrzení.',
  },
  sk: {
    intro: 'Vyberte výrobok pre svoju inštaláciu. Overte rozmery, opíšte prevádzkové podmienky a vyžiadajte si cenu a termín dodania.',
    range: 'Silikónové výrobky', view: 'Zobraziť výrobok', sizes: 'Vyberte rozmer hadice',
    sizeHint: 'Vnútorný / vonkajší priemer v mm. Vybraný rozmer sa prenesie do dopytu.',
    selected: 'Vybraný rozmer', choose: 'Vyberte rozmer', clear: 'Priesvitná silikónová hadica',
    custom: 'Potrebujem iný rozmer', application: 'Výber podľa prevádzkových podmienok',
    applicationText: 'Uveďte médium, teplotu, tlak a rozmery. Vhodnosť materiálu a požadované dokumenty potvrdzujeme pre konkrétny výrobok a použitie.',
    steps: 'Od špecifikácie k dopytu', step1: 'Vyberte výrobok', step1Text: 'Hadica, doska, tesnenie alebo diel podľa výkresu.',
    step2: 'Opíšte podmienky', step2Text: 'Rozmery, médium, teplota, tlak a množstvo.',
    step3: 'Pošlite dopyt', step3Text: 'Vyžiadajte si potvrdenie parametrov, ceny a termínu dodania.',
    menu: 'Hlavná navigácia', open: 'Otvoriť menu', close: 'Zavrieť menu', language: 'Vyberte jazyk',
    customText: 'Pošlite výkres alebo špecifikáciu. Rozmery, materiál a termín vyžadujú individuálne potvrdenie.',
  },
};
